app/models/friend.rb
app/models/user_game.rb
config/database.yml
db/migrate/20191111055836_create_friends.rb
db/migrate/20191111055934_create_user_games.rb
db/migrate/20191111063238_add_online_status_to_users.rb
db/schema.rb
test/fixtures/friends.yml
test/fixtures/user_games.yml
test/models/friend_test.rb
test/models/user_game_test.rb

add initial migration dbases

---

app/models/game.rb
config/database.yml
db/migrate/20191111091054_create_games.rb
db/seeds.rb

aded migration for games and seed data

add games database and seed file

---

Gemfile.lock
app/assets/javascripts/games.js
app/assets/stylesheets/games.scss
app/assets/stylesheets/scaffolds.scss
app/controllers/games_controller.rb
app/helpers/games_helper.rb
app/views/games/_form.html.erb
app/views/games/_game.json.jbuilder
app/views/games/edit.html.erb
app/views/games/index.html.erb
app/views/games/index.json.jbuilder
app/views/games/new.html.erb
app/views/games/show.html.erb
app/views/games/show.json.jbuilder
config/routes.rb
db/schema.rb
test/controllers/games_controller_test.rb
test/fixtures/games.yml
test/models/game_test.rb
test/system/games_test.rb

Choose game  - views of games

---

app/views/games/index.html.erb
app/views/layouts/application.html.erb

fix cards design

---

app/views/games/index.html.erb
app/views/layouts/application.html.erb

fixed navigation bug on mycards

Games cards fix

---

README.md
app/assets/stylesheets/schedules.scss
app/controllers/schedules_controller.rb
app/views/schedules/index.html.erb
app/views/schedules/show.html.erb
db/seeds.rb

Added calendar show page, need usernames to display

Modify calendar

---

app/controllers/user/registrations_controller.rb
app/views/devise/registrations/new.html.erb
config/routes.rb
db/migrate/20191111063238_add_online_status_to_users.rb
db/schema.rb

Enabled Devise-registration controller

Added username to devise

---

app/controllers/games_controller.rb
app/models/game.rb
app/models/games_user.rb
app/models/user.rb
app/models/user_game.rb
app/views/games/index.html.erb
config/database.yml
config/routes.rb
db/migrate/20191111055934_create_games_users.rb
db/migrate/20191111091054_create_games.rb
db/schema.rb
db/seeds.rb

added click to add game to favorites, working
remove from favs button (need  route and controller to be done)

Games click add games to user

---

app/controllers/games_controller.rb
app/views/games/index.html.erb
config/routes.rb

add remove favs from games

---

app/views/games/index.html.erb
db/migrate/20191107083135_add_admin_to_users.rb
db/schema.rb

add admin column to users, check for admin on games index page

add admin column to users, check for admin on games index page

---

app/views/games/index.html.erb
db/migrate/20191107083135_add_admin_to_users.rb
db/schema.rb
db/seeds.rb

seed update for users and friend connections

seed update for users and friend connections

---

app/views/layouts/application.html.erb
db/seeds.rb

edited seed for schedule - event to name
added schedules link for navbar

changed seed

---

app/controllers/games_controller.rb
app/models/friend.rb
app/views/games/index.html.erb
db/seeds.rb

added testing for games to show friends. needs more code to work...
added seed data to connect

Games display friends

---

app/controllers/games_controller.rb
app/models/game.rb
app/models/user.rb
app/views/games/index.html.erb
db/migrate/20191111045135_add_admin_to_users.rb
db/migrate/20191111055135_add_admin_to_users.rb
db/seeds.rb

games display, show friends for logged in, show all for not logged in, update seed

games display, show friends for logged in, show all for not logged in, update seed

---

app/controllers/users_controller.rb
app/views/users/index.html.erb

add table design to index of users, check if friends, show online

add table design to index of users, check if friends, show online

---

app/views/users/index.html.erb

added more generic avatar.....

User avatar

---

app/views/games/index.html.erb

changed favs to hearts

---

app/views/layouts/application.html.erb

removed my games from nav

---

app/views/games/index.html.erb

white heart

---

app/views/games/index.html.erb

border of cards black

---

app/controllers/users_controller.rb
app/views/users/index.html.erb

checked if users liked games matches other users liked games

checked if users liked games matches other users liked games

---

app/views/schedules/edit.html.erb
app/views/schedules/new.html.erb

fixed validation to display field name

fixed validation to display field name

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/homes.scss
app/views/homes/preLogin.html.erb

Added Glowing effects to sign in/sign up

Glowing CSS
